const domains = [
  "Data Science",
  "Machine Learning",
  "Backend Developer",
  "Frontend Developer",
  "Full Stack Developer",
  "DevOps Engineer",
  "Cloud Computing",
  "Database Administrator",
  "System Administrator",
  "Network Engineer",
  "Cybersecurity Analyst",
  "Web Developer",
  "Mobile App Developer",
  "Game Developer",
  "UI/UX Designer",
  "Software Engineer",
  "Embedded Systems",
  "QA Engineer / Tester",
  "IT Support Specialist",
  "Business Analyst",
  "Product Manager",
  "Project Manager",
  "Technical Writer",
  "Data Analyst",
  "Data Engineer",
  "Business Intelligence Analyst",
  "Quantitative Analyst",
  "Automation Engineer",
  "Network Security",
  "Machine Vision Engineer",
  "AR/VR Developer",
  "Blockchain Developer",
  "IoT Developer",
  "Big Data Engineer",
  "Cloud Architect",
  "Natural Language Processing Engineer",
  "Speech Recognition Engineer",
  "Computer Vision Engineer",
  "IT Consultant",
  "AI Ethics Specialist",
  "Chatbot Developer",
  "Robotics Engineer",
  "Bioinformatics Analyst",
  "Firmware Engineer",
  "IT Trainer",
  "Tech Sales Representative",
  "Augmented Reality Designer",
  "Virtual Reality Designer",
  "5G Engineer",
  "Edge Computing Specialist",
  "Digital Marketing Technologist",
];

export default domains;
