const education = [
  "Higher Secondary",
  "Secondary",
  "Bachelor of Arts (B.A)",
  "Bachelor of Science (B.Sc)",
  "Bachelor of Technology (B.Tech)",
  "Bachelor of Commerce (B.Com)",
  "Bachelor of Engineering (B.E)",
  "Bachelor of Business Administration (BBA)",
  "Bachelor of Fine Arts (BFA)",
  "Bachelor of Design (B.Des)",
  "Bachelor of Computer Applications (BCA)",
  "Bachelor of Information Technology (B.IT)",
  "Bachelor of Science in Nursing (B.Sc Nursing)",
  "Bachelor of Architecture (B.Arch)",
  "Bachelor of Pharmacy (B.Pharm)",
  "Bachelor of Laws (LLB)",
  "Bachelor of Social Work (BSW)",
  "Bachelor of Hotel Management (BHM)",
  "Bachelor of Business Management (BBM)",
  "Bachelor of Science in Agriculture (B.Sc Ag)",
  "Bachelor of Physiotherapy (BPT)",
  "Bachelor of Dental Surgery (BDS)",
  "Bachelor of Education (B.Ed)",
  "Bachelor of Journalism and Mass Communication (BJMC)",
  "Bachelor of Animation (B.Animation)",
];

export default education;
