const industry = [
  "Agriculture",
  "Automotive",
  "Business and Management",
  "Computer Software",
  "Construction",
  "Customer Service",
  "Education and Training",
  "Electronics",
  "Energy and Utilities",
  "Environmental Services",
  "Fashion and Apparel",
  "Finance",
  "Food and Beverage",
  "Government and Public Administration",
  "Healthcare",
  "Hospitality and Tourism",
  "Information Technology (IT)",
  "Legal Services",
  "Manufacturing",
  "Marketing and Advertising",
  "Media and Entertainment",
  "Nonprofit and Social Organizations",
  "Pharmaceuticals",
  "Real Estate",
  "Retail",
  "Science and Research",
  "Social Services",
  "Sports and Recreation",
  "Telecommunications",
  "Transportation and Logistics",
];

export default industry;
