const locations = [
  { city: "New York City", state: "New York" },
  { city: "Los Angeles", state: "California" },
  { city: "Chicago", state: "Illinois" },
  { city: "Houston", state: "Texas" },
  { city: "Phoenix", state: "Arizona" },
  { city: "Philadelphia", state: "Pennsylvania" },
  { city: "San Antonio", state: "Texas" },
  { city: "San Diego", state: "California" },
  { city: "Dallas", state: "Texas" },
  { city: "San Jose", state: "California" },
  { city: "Austin", state: "Texas" },
  { city: "Jacksonville", state: "Florida" },
  { city: "San Francisco", state: "California" },
  { city: "Columbus", state: "Ohio" },
  { city: "Indianapolis", state: "Indiana" },
  { city: "Seattle", state: "Washington" },
  { city: "Denver", state: "Colorado" },
  { city: "Washington", state: "District of Columbia" },
  { city: "Boston", state: "Massachusetts" },
  { city: "El Paso", state: "Texas" },
  { city: "Nashville", state: "Tennessee" },
  { city: "Detroit", state: "Michigan" },
  { city: "Oklahoma City", state: "Oklahoma" },
  { city: "Portland", state: "Oregon" },
  { city: "Las Vegas", state: "Nevada" },
  { city: "Memphis", state: "Tennessee" },
  { city: "Louisville", state: "Kentucky" },
  { city: "Baltimore", state: "Maryland" },
  { city: "Milwaukee", state: "Wisconsin" },
  { city: "Albuquerque", state: "New Mexico" },
  { city: "Tucson", state: "Arizona" },
  { city: "Fresno", state: "California" },
  { city: "Sacramento", state: "California" },
  { city: "Kansas City", state: "Missouri" },
  { city: "Long Beach", state: "California" },
  { city: "Mesa", state: "Arizona" },
  { city: "Atlanta", state: "Georgia" },
  { city: "Colorado Springs", state: "Colorado" },
  { city: "Virginia Beach", state: "Virginia" },
  { city: "Raleigh", state: "North Carolina" },
  { city: "Omaha", state: "Nebraska" },
  { city: "Miami", state: "Florida" },
  { city: "Oakland", state: "California" },
  { city: "Minneapolis", state: "Minnesota" },
  { city: "Tulsa", state: "Oklahoma" },
];

export default locations;
